server:
 port: 9007


spring:
  application:
    name: community-search
  data:
    elasticsearch:
      cluster-nodes:  192.168.29.170:9300

eureka:
  client:
    service-url:
      defaultZone: http://192.168.29.125:6868/eureka
  instance:
    prefer-ip-address: true
